# Generated by Django 6.0.2 on 2026-02-26 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ishbor', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='employerprofile',
            name='company_address',
            field=models.TextField(default='andijon'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='employerprofile',
            name='company_phone',
            field=models.CharField(default='+998901234567', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='employerprofile',
            name='stir',
            field=models.CharField(default='0000000000', max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='employerprofile',
            name='company_name',
            field=models.CharField(max_length=255),
        ),
    ]
