# Generated by Django 6.0.2 on 2026-03-04 05:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ishbor', '0006_remove_candidateprofile_full_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='application',
            name='cv_file',
        ),
        migrations.AddField(
            model_name='application',
            name='resume',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ishbor.resume'),
        ),
    ]
