# Generated by Django 6.0.2 on 2026-03-04 05:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ishbor', '0007_remove_application_cv_file_application_resume'),
    ]

    operations = [
        migrations.CreateModel(
            name='Interview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_time', models.DateTimeField(verbose_name='Suhbat vaqti')),
                ('location_link', models.URLField(max_length=500, verbose_name='Suhbat manzili yoki Link (Zoom/Google Meet)')),
                ('notes', models.TextField(blank=True, null=True, verbose_name="Qo'shimcha eslatmalar")),
                ('status', models.CharField(choices=[('pending', 'Kutilmoqda'), ('accepted', 'Nomzod qabul qildi'), ('rejected', 'Nomzod rad etdi')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('application', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='interview', to='ishbor.application')),
            ],
        ),
    ]
