# Generated by Django 6.0.2 on 2026-04-02 06:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ishbor', '0008_interview'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='consent',
            options={'ordering': ['-accepted_at']},
        ),
        migrations.AddField(
            model_name='candidateprofile',
            name='gdpr_consent_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='candidateprofile',
            name='marketing_consent',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='consent',
            name='consent_type',
            field=models.CharField(choices=[('registration', "Ro'yxatdan o'tish roziligi"), ('gdpr', 'GDPR roziligi'), ('marketing', 'Marketing roziligi'), ('data_processing', "Ma'lumotlarni qayta ishlash roziligi")], default='registration', max_length=30),
        ),
        migrations.AddField(
            model_name='consent',
            name='ip_address',
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='consent',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='employerprofile',
            name='gdpr_consent',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='employerprofile',
            name='gdpr_consent_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='employerprofile',
            name='marketing_consent',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='consent',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consents', to=settings.AUTH_USER_MODEL),
        ),
    ]
