# Generated by Django 6.0.3 on 2026-04-12 09:07

import ishbor.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ishbor', '0009_alter_consent_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='consent',
            name='policy_version',
            field=models.CharField(default='1.0', max_length=10, verbose_name='Siyosat versiyasi'),
        ),
        migrations.AddField(
            model_name='employerprofile',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='candidateprofile',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=ishbor.models.upload_to_candidates),
        ),
        migrations.AlterField(
            model_name='certificate',
            name='file',
            field=models.FileField(upload_to=ishbor.models.upload_to_certificates),
        ),
        migrations.AlterField(
            model_name='employerprofile',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to=ishbor.models.upload_to_company_logos),
        ),
        migrations.AlterField(
            model_name='resume',
            name='file',
            field=models.FileField(upload_to=ishbor.models.upload_to_resumes),
        ),
    ]
