# Generated by Django 6.0.3 on 2026-04-12 09:16

import ishbor.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ishbor', '0010_consent_policy_version_employerprofile_updated_at_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='application',
            options={'verbose_name': 'Ariza', 'verbose_name_plural': 'Arizalar'},
        ),
        migrations.AlterModelOptions(
            name='candidateprofile',
            options={'verbose_name': 'Nomzod profili', 'verbose_name_plural': 'Nomzodlar profillari'},
        ),
        migrations.AlterModelOptions(
            name='certificate',
            options={'verbose_name': 'Sertifikat', 'verbose_name_plural': 'Sertifikatlar'},
        ),
        migrations.AlterModelOptions(
            name='consent',
            options={'ordering': ['-accepted_at'], 'verbose_name': 'Rozilik (Consent)', 'verbose_name_plural': 'Roziliklar (Consents)'},
        ),
        migrations.AlterModelOptions(
            name='employerprofile',
            options={'verbose_name': 'Ish beruvchi profili', 'verbose_name_plural': 'Ish beruvchilar profillari'},
        ),
        migrations.AlterModelOptions(
            name='experience',
            options={'verbose_name': 'Tajriba', 'verbose_name_plural': 'Tajribalar'},
        ),
        migrations.AlterModelOptions(
            name='interview',
            options={'verbose_name': 'Suhbat', 'verbose_name_plural': 'Suhbatlar'},
        ),
        migrations.AlterModelOptions(
            name='resume',
            options={'verbose_name': 'Rezyume', 'verbose_name_plural': 'Rezyumelar'},
        ),
        migrations.AlterModelOptions(
            name='vacancy',
            options={'ordering': ['-created_at'], 'verbose_name': 'Vakansiya', 'verbose_name_plural': 'Vakansiyalar'},
        ),
        migrations.AlterField(
            model_name='application',
            name='cover_letter',
            field=models.TextField(blank=True, null=True, verbose_name="Qo'shimcha xat (Cover Letter)"),
        ),
        migrations.AlterField(
            model_name='application',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan sana'),
        ),
        migrations.AlterField(
            model_name='application',
            name='status',
            field=models.CharField(choices=[('pending', 'Kutilmoqda'), ('reviewed', "Ko'rib chiqildi"), ('accepted', 'Qabul qilindi'), ('rejected', 'Rad etildi')], default='pending', max_length=20, verbose_name='Holat'),
        ),
        migrations.AlterField(
            model_name='candidateprofile',
            name='gdpr_consent',
            field=models.BooleanField(default=False, verbose_name='GDPR roziligi'),
        ),
        migrations.AlterField(
            model_name='candidateprofile',
            name='gdpr_consent_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='GDPR rozilik sanasi'),
        ),
        migrations.AlterField(
            model_name='candidateprofile',
            name='marketing_consent',
            field=models.BooleanField(default=False, verbose_name='Marketing roziligi'),
        ),
        migrations.AlterField(
            model_name='candidateprofile',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Yangilangan sana'),
        ),
        migrations.AlterField(
            model_name='certificate',
            name='file',
            field=models.FileField(upload_to=ishbor.models.upload_to_certificates, verbose_name='Fayl'),
        ),
        migrations.AlterField(
            model_name='certificate',
            name='issued_date',
            field=models.DateField(verbose_name='Berilgan sana'),
        ),
        migrations.AlterField(
            model_name='consent',
            name='accepted_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Qabul qilingan vaqt'),
        ),
        migrations.AlterField(
            model_name='consent',
            name='ip_address',
            field=models.GenericIPAddressField(blank=True, null=True, verbose_name='IP manzil'),
        ),
        migrations.AlterField(
            model_name='employerprofile',
            name='gdpr_consent',
            field=models.BooleanField(default=False, verbose_name='GDPR roziligi'),
        ),
        migrations.AlterField(
            model_name='employerprofile',
            name='gdpr_consent_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='GDPR rozilik sanasi'),
        ),
        migrations.AlterField(
            model_name='employerprofile',
            name='marketing_consent',
            field=models.BooleanField(default=False, verbose_name='Marketing roziligi'),
        ),
        migrations.AlterField(
            model_name='employerprofile',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Yangilangan sana'),
        ),
        migrations.AlterField(
            model_name='experience',
            name='description',
            field=models.TextField(blank=True, verbose_name='Tavsif'),
        ),
        migrations.AlterField(
            model_name='experience',
            name='end_date',
            field=models.DateField(blank=True, null=True, verbose_name='Tugash sanasi'),
        ),
        migrations.AlterField(
            model_name='experience',
            name='start_date',
            field=models.DateField(verbose_name='Boshlanish sanasi'),
        ),
        migrations.AlterField(
            model_name='interview',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan sana'),
        ),
        migrations.AlterField(
            model_name='interview',
            name='status',
            field=models.CharField(choices=[('pending', 'Kutilmoqda'), ('accepted', 'Nomzod qabul qildi'), ('rejected', 'Nomzod rad etdi')], default='pending', max_length=20, verbose_name='Holati'),
        ),
        migrations.AlterField(
            model_name='resume',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan sana'),
        ),
        migrations.AlterField(
            model_name='resume',
            name='file',
            field=models.FileField(upload_to=ishbor.models.upload_to_resumes, verbose_name='Fayl'),
        ),
        migrations.AlterField(
            model_name='resume',
            name='title',
            field=models.CharField(max_length=100, verbose_name='Sarlavha'),
        ),
        migrations.AlterField(
            model_name='resume',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Yangilangan sana'),
        ),
        migrations.AlterField(
            model_name='user',
            name='phone',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Telefon raqami'),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('candidate', 'Ish izlovchi'), ('employer', 'Ish beruvchi')], max_length=20, verbose_name='Rol'),
        ),
        migrations.AlterField(
            model_name='vacancy',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan sana'),
        ),
        migrations.AlterField(
            model_name='vacancy',
            name='deadline',
            field=models.DateField(blank=True, null=True, verbose_name='Oxirgi muddat'),
        ),
        migrations.AlterField(
            model_name='vacancy',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Faol holatda'),
        ),
    ]
